#!/usr/bin/env python2
#coding=UTF-8

# Uso: ./tabular [parámetros del programa C++]
#
# Ejemplos:
# ./tabular --muestra data/X1.txt --metodo biseccion --a0 1 --b0 100
# ./tabular --muestra data/X2.txt --metodo newton --p0 10
#
# Salida:
# Imprime en la salida standard una tabla en formato CSV con la salida
# del siguiente comando
#
#   ./dgg --csv [parámetros del programa C++] [parámetros tabulados i]
#
# Donde [parámetros tabulados i] es la i-ésima combinación de parámetros
# (--precision [51, 30, 10] --error [0.001, 0.01, 0.1] [--relativo]).
#
# Uso alternativo: ./tabular --headers
#
# Salida: una única línea con los headers de 

import sys
import commands

precisiones = [51, 20, 15]
criterios   = ["", "--relativo"]
errores     = [0.001, 0.01, 0.1]

# Imprimo header
status, output = commands.getstatusoutput("./dgg --csvheaders")
print output

# Imprimo cada fila de la tabla
for t in precisiones:
    for c in criterios:
        for e in errores:
            # Genero el comando a ejecutar
            parametros = "-t " + str(t) + " -e " + str(e) + " " + c
            command = "./dgg --csv " + " ".join(sys.argv[1:]) + " " + parametros

            # Ejecuto el programa C++, imprimo la salida y me la guardo
            status, output = commands.getstatusoutput(command)

            # Imprimo el resultado del programa C++ en la salida standard
            print output

            # Si el programa C++ generó un error, termino el script
            if status != 0:
                sys.exit(-1)